Repository realponto-project/realponto-dash, pull requests merged in 2021-05, with the labels that each got.

#91 chore: add invite email, recover pass and reset pass
  package.json
  src/App.js
  src/Assets/pass.svg
  src/Assets/resetPass.svg
  src/Containers/Accreditation/ForgetPass/index.js
  src/Containers/Accreditation/ForgetPass/style.module.css
  src/Containers/Accreditation/Register/index.js
  src/Containers/Accreditation/Register/style.module.css
  src/Containers/Accreditation/ResetPass/index.js
  src/Containers/Accreditation/ResetPass/style.module.css
  src/Containers/Login/index.js
  src/Containers/Onboarding/UpdatePassword/index.js
  src/Containers/Onboarding/Welcome/index.js
  src/Pages/Accreditation/Register/ForgotPass.js
  src/Pages/Accreditation/Register/ResetPass.js
  src/Pages/Login/index.js
  src/Pages/Onboarding/index.js
  src/Services/User/index.js
  src/utils/axiosInstance.js
  yarn.lock
Labels: Priority high, enhancement, front-end

#96 Fix/catalog
  src/Components/Layout/index.js
  src/Containers/Catalog/Details/style.module.css
  src/Containers/Product/Detail/index.js
  src/Pages/Product/Detail/index.js
  src/Routes/root.js
  src/Services/Product/index.js
  src/index.css
Labels: front-end

#105 chore: resend invite member
  src/Containers/MyTeam/Manager/UserList/index.js
  src/Containers/MyTeam/Manager/index.js
  src/Pages/MyTeam/index.js
  src/Pages/Onboarding/index.js
  src/Services/User/index.js
Labels: backend, front-end

#101 Add/logo and nick name
  src/App.js
  src/Containers/Accreditation/Register/index.js
  src/Containers/Catalog/Manager/index.js
  src/Containers/Catalog/Manager/style.module.css
  src/Containers/MyInfo/index.js
  src/Containers/MyInfo/style.module.css
  src/Containers/Product/Detail/index.js
  src/Containers/Product/Manager/index.js
  src/Pages/Accreditation/Register/index.js
  src/Pages/Catalog/Manager.js
  src/Pages/MyInfo/index.js
  src/Pages/Product/Manager/index.js
  src/Services/Catalog/index.js
  src/Services/Company/index.js
  src/utils/validators.js
Labels: backend, front-end

#103 Add/keyboard shortcuts
  src/Containers/PDV/CustomerInfo/index.js
  src/Containers/PDV/Detail/index.js
  src/Containers/PDV/Detail/style.module.css
  src/Containers/PDV/ModalSearchBarCode.js
  src/Containers/PDV/PaymentInfo/index.js
  src/Containers/PDV/ProductList/index.js
  src/Pages/PDV/index.js
Labels: front-end

#98 Add/flag catalog
  src/Containers/Catalog/Details/index.js
  src/Containers/Catalog/Details/style.module.css
  src/Containers/Catalog/Manager/index.js
  src/Containers/Product/Add/index.js
  src/Containers/Product/Edit/index.js
  src/Containers/Product/Manager/index.js
  src/Pages/Catalog/Details.js
  src/Pages/Catalog/Manager.js
  src/Pages/Product/Manager/index.js
Labels: backend, front-end
