Repository realponto-project/realponto-dash, pull requests merged in 2021-03, with the labels that each got.

#15 Self accreditation
  .eslintcache
  .storybook/preview.js
  package.json
  public/index.html
  src/App.js
  src/Assets/allTheData.svg
  src/Assets/asArveresSomosNozes.svg
  src/Assets/logo.svg
  src/Assets/onlineResume.svg
  src/Containers/Accreditation/Register/index.js
  src/Containers/Accreditation/Register/style.module.css
  src/Containers/Accreditation/Success/index.js
  src/Containers/Accreditation/Success/style.module.css
  src/Containers/Login/index.js
  src/Containers/Login/meets.svg
  src/Containers/Login/style.module.css
  src/Pages/Accreditation/Register/Success.js
  src/Pages/Accreditation/Register/index.js
  src/Pages/Login/index.js
  src/Services/Company/index.js
  src/index.css
  src/stories/Pages/Accreditation/Company.js
  src/stories/Pages/Accreditation/Login.js
  src/stories/Pages/Accreditation/Success.js
  src/utils/validators.js
  yarn.lock
Labels: enhancement, front-end

#17 Create/product
  .eslintcache
  src/Containers/Product/Add/index.js
  src/Containers/Product/Edit/index.js
  src/Containers/Product/Manager/ProductList/index.js
  src/Containers/Product/Manager/index.js
Labels: front-end

#16 Alter/signature
  .eslintcache
  package-lock.json
  package.json
  src/Components/AdBanner/index.js
  src/Components/AdSide/index.js
  src/Containers/Plans/alxa.svg
  src/Containers/Plans/button.svg
  src/Containers/Plans/completed.svg
  src/Containers/Plans/goals.svg
  src/Containers/Plans/index.js
  src/Containers/Plans/mastercard.svg
  src/Containers/Plans/style.module.css
  src/Containers/Plans/visa.svg
  src/Containers/Product/Add/index.js
  src/Containers/Product/Edit/index.js
  src/Containers/Product/Manager/ProductList/index.js
  src/Containers/Product/Manager/index.js
  src/Routes/root.js
  src/Services/Plans/index.js
  src/Services/Subscription/index.js
  src/config/api_keys.js
  yarn.lock
Labels: front-end

#19 Create/status
  .eslintcache
  src/Components/Header/index.js
  src/Containers/Status/Add/index.js
  src/Containers/Status/Edit/index.js
  src/Containers/Status/Manager/StatusList/index.js
  src/Containers/Status/Manager/index.js
  src/Pages/Login/index.js
  src/Pages/Status/Manager/index.js
  src/Redux/actions/statusSearch.js
  src/Redux/reducers/index.js
  src/Redux/reducers/statusSearch.js
  src/Routes/root.js
  src/Services/Status/index.js
Labels: front-end

#18 chore: interaction pagarme
  .eslintcache
  package.json
  src/Containers/Plans/index.js
  src/Services/pagarme.js
  src/config/api_keys.js
  yarn.lock
Labels: front-end

#35 Create/onboarding
  .eslintcache
  .eslintrc.js
  src/App.js
  src/Containers/Onboarding/Form/index.js
  src/Containers/Onboarding/UpdatePassword/index.js
  src/Containers/Onboarding/Welcome/index.js
  src/Containers/Onboarding/Welcome/mira.svg
  src/Containers/Onboarding/Welcome/monitoramento.svg
  src/Containers/Onboarding/Welcome/security.svg
  src/Containers/Onboarding/alxa.svg
  src/Containers/Onboarding/index.js
  src/Containers/Onboarding/onboarding.svg
  src/Containers/Onboarding/style.module.css
  src/Pages/Login/index.js
  src/Pages/Onboarding/index.js
  src/Routes/root.js
Labels: front-end

#36 chore: bug customer, product, status, subscription, plan
  src/Assets/alxa-plus.svg
  src/Components/Layout/index.js
  src/Containers/Customer/Add/index.js
  src/Containers/Customer/Detail/index.js
  src/Containers/Customer/Manager/CustomerList/index.js
  src/Containers/Customer/Manager/index.js
  src/Containers/Onboarding/index.js
  src/Containers/Plans/index.js
  src/Containers/Product/Add/index.js
  src/Containers/Product/Edit/index.js
  src/Containers/Status/Manager/StatusList/index.js
  src/Pages/Customer/Detail/index.js
  src/Pages/Login/index.js
  src/Pages/Onboarding/index.js
  src/Pages/Plans/index.js
  src/Redux/actions/subscription.js
  src/Redux/reducers/index.js
  src/Redux/reducers/subscription.js
  src/Routes/root.js
  src/Services/Subscription/index.js
  src/Services/pagarme.js
Labels: bug, front-end
