Repository realponto-project/realponto-dash, pull requests merged in 2021-04, with the labels that each got.

#37 Feature/pdv
  .eslintignore
  .eslintrc.js
  package.json
  src/App.js
  src/Components/Cupom/index.js
  src/Components/Header/index.js
  src/Containers/PDV/Checkout/index.js
  src/Containers/PDV/Checkout/style.module.css
  src/Containers/PDV/ModalSearchBarCode.js
  src/Containers/PDV/ProductList/index.js
  src/Containers/PDV/ProductList/style.module.css
  src/Containers/PDV/index.js
  src/Containers/PDV/style.module.css
  src/Pages/Logged/index.js
  src/Pages/PDV/index.js
  src/Redux/reducers/formPdv.js
  src/Redux/reducers/index.js
  src/Services/Order/index.js
  src/Services/Product/index.js
  src/utils/index.js
  yarn.lock
Labels: enhancement, front-end

#42 Corrigindo erros no front
  src/Containers/Customer/Add/index.js
  src/Containers/MyTeam/Manager/index.js
  src/Containers/Onboarding/Form/index.js
  src/Containers/Onboarding/UpdatePassword/index.js
  src/Containers/Plans/index.js
  src/Containers/Product/Add/index.js
  src/Pages/Product/Manager/index.js
  src/Routes/root.js
  yarn.lock
Labels: front-end

#49 chore: page report (FALTA FINALIZAR)
  src/Components/Layout/index.js
  src/Containers/Report/index.js
  src/Containers/Report/style.module.css
  src/Pages/Order/Manager/index.js
  src/Pages/Report/index.js
  src/Routes/root.js
Labels: front-end

#75 Fix/pdv/set form pdv
  package.json
  src/Containers/PDV/index.js
  src/Pages/PDV/index.js
Labels: Priority high, bug, front-end

#80 fix: parseValuePTbr
  package.json
  src/Containers/MyTeam/Manager/UserList/index.js
  src/utils/Masks/myInfoMasks.js
Labels: bug, front-end

#81 chore: get data for pie
  src/Assets/empty.svg
  src/Containers/Product/Detail/PieChart/index.js
  src/Containers/Product/Detail/index.js
  src/Pages/Product/Detail/index.js
  src/Services/Product/index.js
Labels: backend, front-end

#84 Movement
  .eslintrc.js
  src/Containers/Report/ModalMovement/index.js
  src/Containers/Report/index.js
  src/Pages/Report/index.js
  src/Services/Transaction/index.js
Labels: Priority high, backend, enhancement, front-end

#90 chore: crete catalog
  src/App.js
  src/Containers/Catalog/Details/index.js
  src/Containers/Catalog/Details/style.module.css
  src/Containers/Catalog/Manager/index.js
  src/Containers/Catalog/Manager/style.module.css
  src/Pages/Catalog/Details.js
  src/Pages/Catalog/Manager.js
  src/Services/Catalog/index.js
  src/stories/Pages/Catalog/detail.js
  src/stories/Pages/Catalog/manager.js
  src/utils/axiosInstance.js
Labels: backend, enhancement, front-end
